env:
  browser: true
  es6: true
extends:
  - 'eslint:recommended'
  - 'plugin:react/recommended'
  - 'plugin:react-hooks/recommended'
globals:
  Atomics: readonly
  SharedArrayBuffer: readonly
parserOptions:
  ecmaFeatures:
    jsx: true
  ecmaVersion: 2018
  sourceType: module
plugins:
  - react
  - react-hooks
  - prettier
rules: {
  quotes: ["error", "single"],
  semi: ["error", "never"],
  react/prop-types: "off",
  no-unused-vars: 1,
  no-case-declarations: 0,
  react-hooks/rules-of-hooks: "error",
  prettier/prettier: "warn",
  indent: [
      error,
      2
  ],
  no-console: [ 2, { allow: [ warn, error ] } ],
  react/display-name: 0,
  react-hooks/exhaustive-deps: 0,
  import/no-unresolved: 0,
  linebreak-style: 0,
  import/no-extraneous-dependencies: 0,
  react/jsx-filename-extension: 0,
  no-underscore-dangle: 0,
  import/prefer-default-export: 0,
  max-len: [
      1,
      200
  ],
  no-plusplus: 0,
  no-continue: 0,
  consistent-return: 0,
  react/jsx-props-no-spreading: 1,
  no-shadow: 0,
  jsx-a11y/click-events-have-key-events: 0,
  jsx-a11y/no-noninteractive-element-interactions: 0,
  no-nested-ternary: 0,
  react/button-has-type: 0
}