version: '3'

services:
  db:
    container_name: analytics_db_prod
    image: postgres
    ports:
      - "6435:5432"
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=poi987Qw
      - POSTGRES_DB=analytics_db
    networks:
      nginx_net:
    volumes:
      - ./dbs/postgres-data-prod:/var/lib/postgresql
  backend:
    container_name: analytics_backend_prod
    build:
      context: ./application
      dockerfile: Dockerfile-prod
    command: bash -c "sleep 3 && python manage.py makemigrations && python manage.py makemigrations && python manage.py migrate && python manage.py collectstatic --noinput && gunicorn analytics_project.wsgi -b 0.0.0.0:8001 --workers 2";
    networks:
      nginx_net:
    volumes:
      - ./application:/application
    expose:
      - 8000
    restart: always
    links:
      - db
  nginx:
    image: nginx:alpine
    container_name: nginx
    ports:
      - "80:80"
      - "443:443"
    networks:
      nginx_net:
    volumes:
      - ./application/media:/backend/src/media
      - ./application/static-backend:/backend/src/static-backend
      - ./frontend/build:/frontend/src
      - ./nginx/ssl:/etc/nginx/conf.d
      - ./nginx/ssl/data/certbot/conf:/etc/letsencrypt
      - ./nginx/ssl/data/certbot/www:/var/www/certbot
    depends_on:
      - backend
  certbot:
    image: certbot/certbot
    container_name: certbot
    networks:
      nginx_net:
    volumes:
      - ./nginx/ssl/data/certbot/conf:/etc/letsencrypt
      - ./nginx/ssl/data/certbot/www:/var/www/certbot
      # - web-root:/var/www/html

    # command: certonly --webroot --webroot-path=/var/www/html --email antongovorov@gmail.com --agree-tos --no-eff-email --staging -d op.itmo.ru
volumes:
  postgres_data:
#  certbot-etc:
#  certbot-var:
#  web-root:
#    driver: local
#    driver_opts:
#      type: none
#      device: /home/user/analytics_backend/tests
#      o: bind

networks:
  nginx_net:
    name: nginx_net
